export const tableDefinitions = {
  Departamento: {
    label: 'Departamentos',
    description: 'Departamentos operativos donde se ubican las sucursales.',
    primaryKey: 'ID_DEPARTAMENTO',
    accent: 'from-emerald-500/20 to-emerald-500/5',
    defaultSort: { field: 'ID_DEPARTAMENTO', direction: 'asc' },
    fields: [
      { name: 'ID_DEPARTAMENTO', label: 'ID', type: 'number', required: true },
      { name: 'NOMBRE_DEPARTAMENTO', label: 'Nombre', type: 'text', required: true },
    ],
  },
  Municipio: {
    label: 'Municipios',
    description: 'Municipios por departamento.',
    primaryKey: 'ID_MUNICIPIO',
    accent: 'from-sky-500/20 to-sky-500/5',
    defaultSort: { field: 'ID_MUNICIPIO', direction: 'asc' },
    fields: [
      { name: 'ID_MUNICIPIO', label: 'ID', type: 'number', required: true },
      { name: 'ID_DEPARTAMENTO', label: 'Departamento', type: 'number', required: true },
      { name: 'NOMBRE_MUNICIPIO', label: 'Nombre', type: 'text', required: true },
    ],
  },
  Sucursal: {
    label: 'Sucursales',
    description: 'Puntos de venta físicos.',
    primaryKey: 'ID_SUCURSAL',
    accent: 'from-purple-500/20 to-purple-500/5',
    defaultSort: { field: 'ID_SUCURSAL', direction: 'asc' },
    fields: [
      { name: 'ID_SUCURSAL', label: 'ID', type: 'number', required: true },
      { name: 'ID_MUNICIPIO', label: 'Municipio', type: 'number', required: true },
      { name: 'DIRECCION', label: 'Dirección', type: 'text', required: true },
      { name: 'TIPO', label: 'Tipo', type: 'text', required: false },
    ],
  },
  Puesto: {
    label: 'Puestos',
    description: 'Catálogo de puestos con salarios base.',
    primaryKey: 'ID_PUESTO',
    accent: 'from-amber-500/20 to-amber-500/5',
    defaultSort: { field: 'ID_PUESTO', direction: 'asc' },
    fields: [
      { name: 'ID_PUESTO', label: 'ID', type: 'number', required: true },
      { name: 'NOMBRE_PUESTO', label: 'Nombre', type: 'text', required: true },
      { name: 'SALARIO_BASE', label: 'Salario Base', type: 'decimal', required: false },
    ],
  },
  Empleado: {
    label: 'Empleados',
    description: 'Personal registrado por puesto y sucursal.',
    primaryKey: 'ID_EMPLEADO',
    accent: 'from-rose-500/20 to-rose-500/5',
    defaultSort: { field: 'ID_EMPLEADO', direction: 'asc' },
    fields: [
      { name: 'ID_EMPLEADO', label: 'ID', type: 'number', required: true },
      { name: 'ID_SUCURSAL', label: 'Sucursal', type: 'number', required: true },
      { name: 'ID_PUESTO', label: 'Puesto', type: 'number', required: true },
      { name: 'NOMBRE', label: 'Nombre', type: 'text', required: true },
      { name: 'APELLIDO', label: 'Apellido', type: 'text', required: true },
      { name: 'SALARIO', label: 'Salario', type: 'decimal', required: false },
    ],
  },
  Proveedor: {
    label: 'Proveedores',
    description: 'Listado de proveedores autorizados.',
    primaryKey: 'ID_PROVEEDOR',
    accent: 'from-lime-500/20 to-lime-500/5',
    defaultSort: { field: 'ID_PROVEEDOR', direction: 'asc' },
    fields: [
      { name: 'ID_PROVEEDOR', label: 'ID', type: 'number', required: true },
      { name: 'NOMBRE_PROVEEDOR', label: 'Nombre', type: 'text', required: true },
    ],
  },
  Tipo_Producto: {
    label: 'Tipos de producto',
    description: 'Clasificación de productos.',
    primaryKey: 'ID_TIPO_PRODUCTO',
    accent: 'from-cyan-500/20 to-cyan-500/5',
    defaultSort: { field: 'ID_TIPO_PRODUCTO', direction: 'asc' },
    fields: [
      { name: 'ID_TIPO_PRODUCTO', label: 'ID', type: 'number', required: true },
      { name: 'CATEGORIA', label: 'Categoría', type: 'text', required: true },
    ],
  },
  Producto: {
    label: 'Productos',
    description: 'Catálogo completo de productos.',
    primaryKey: 'ID_PRODUCTO',
    accent: 'from-fuchsia-500/20 to-fuchsia-500/5',
    defaultSort: { field: 'ID_PRODUCTO', direction: 'asc' },
    fields: [
      { name: 'ID_PRODUCTO', label: 'ID', type: 'number', required: true },
      { name: 'ID_TIPO_PRODUCTO', label: 'Tipo', type: 'number', required: true },
      { name: 'ID_PROVEEDOR', label: 'Proveedor', type: 'number', required: true },
      { name: 'NOMBRE_PRODUCTO', label: 'Nombre', type: 'text', required: true },
      { name: 'PRECIO_VENTA', label: 'Precio Venta', type: 'decimal', required: false },
      { name: 'COSTO', label: 'Costo', type: 'decimal', required: false },
      { name: 'STOCK_MINIMO', label: 'Stock Mínimo', type: 'number', required: false },
    ],
  },
  Inventario_Sucursal: {
    label: 'Inventario por sucursal',
    description: 'Cantidad disponible por sucursal.',
    primaryKey: ['ID_SUCURSAL', 'ID_PRODUCTO'],
    accent: 'from-blue-500/20 to-blue-500/5',
    defaultSort: { field: 'ID_SUCURSAL', direction: 'asc' },
    fields: [
      { name: 'ID_SUCURSAL', label: 'Sucursal', type: 'number', required: true },
      { name: 'ID_PRODUCTO', label: 'Producto', type: 'number', required: true },
      { name: 'CANTIDAD', label: 'Cantidad', type: 'number', required: true },
    ],
  },
  Cliente: {
    label: 'Clientes',
    description: 'Directorio de clientes finales.',
    primaryKey: 'ID_CLIENTE',
    accent: 'from-teal-500/20 to-teal-500/5',
    defaultSort: { field: 'ID_CLIENTE', direction: 'asc' },
    fields: [
      { name: 'ID_CLIENTE', label: 'ID', type: 'number', required: true },
      { name: 'NOMBRE_CLIENTE', label: 'Nombre', type: 'text', required: false },
      { name: 'APELLIDO', label: 'Apellido', type: 'text', required: false },
      { name: 'TELEFONO', label: 'Teléfono', type: 'text', required: false },
    ],
  },
  Tipo_Pedido: {
    label: 'Tipos de pedido',
    description: 'Modalidades de pedido.',
    primaryKey: 'ID_TIPO_PEDIDO',
    accent: 'from-pink-500/20 to-pink-500/5',
    defaultSort: { field: 'ID_TIPO_PEDIDO', direction: 'asc' },
    fields: [
      { name: 'ID_TIPO_PEDIDO', label: 'ID', type: 'number', required: true },
      { name: 'NOMBRE', label: 'Nombre', type: 'text', required: false },
    ],
  },
  Pedido: {
    label: 'Pedidos',
    description: 'Encabezado de pedidos de clientes.',
    primaryKey: 'ID_PEDIDO',
    accent: 'from-indigo-500/20 to-indigo-500/5',
    defaultSort: { field: 'ID_PEDIDO', direction: 'asc' },
    fields: [
      { name: 'ID_PEDIDO', label: 'ID', type: 'number', required: true },
      { name: 'ID_CLIENTE', label: 'Cliente', type: 'number', required: false },
      { name: 'ID_TIPO_PEDIDO', label: 'Tipo Pedido', type: 'number', required: false },
      { name: 'FECHA_PEDIDO', label: 'Fecha', type: 'date', required: false },
      { name: 'TOTAL', label: 'Total', type: 'decimal', required: false },
    ],
  },
  Detalle_Pedido: {
    label: 'Detalle de pedido',
    description: 'Productos por pedido.',
    primaryKey: ['ID_PEDIDO', 'ID_PRODUCTO'],
    accent: 'from-emerald-400/20 to-emerald-400/5',
    defaultSort: { field: 'ID_PEDIDO', direction: 'asc' },
    fields: [
      { name: 'ID_PEDIDO', label: 'Pedido', type: 'number', required: true },
      { name: 'ID_PRODUCTO', label: 'Producto', type: 'number', required: true },
      { name: 'CANTIDAD', label: 'Cantidad', type: 'number', required: true },
      { name: 'PRECIO_UNITARIO', label: 'Precio Unitario', type: 'decimal', required: false },
    ],
  },
  Entrega: {
    label: 'Entregas',
    description: 'Seguimiento de entregas por pedido.',
    primaryKey: 'ID_ENTREGA',
    accent: 'from-yellow-500/20 to-yellow-500/5',
    defaultSort: { field: 'ID_ENTREGA', direction: 'asc' },
    fields: [
      { name: 'ID_ENTREGA', label: 'ID', type: 'number', required: true },
      { name: 'ID_PEDIDO', label: 'Pedido', type: 'number', required: false },
      { name: 'ID_SUCURSAL', label: 'Sucursal', type: 'number', required: false },
      { name: 'FECHA_ESTIMADA', label: 'Fecha Estimada', type: 'date', required: false },
    ],
  },
  Forma_Pago: {
    label: 'Formas de pago',
    description: 'Métodos aceptados.',
    primaryKey: 'ID_FORMAPAGO',
    accent: 'from-violet-500/20 to-violet-500/5',
    defaultSort: { field: 'ID_FORMAPAGO', direction: 'asc' },
    fields: [
      { name: 'ID_FORMAPAGO', label: 'ID', type: 'number', required: true },
      { name: 'NOMBRE_METODO', label: 'Método', type: 'text', required: true },
    ],
  },
  Venta: {
    label: 'Ventas',
    description: 'Operaciones de venta consolidadas.',
    primaryKey: 'ID_VENTA',
    accent: 'from-red-500/20 to-red-500/5',
    defaultSort: { field: 'ID_VENTA', direction: 'desc' },
    fields: [
      { name: 'ID_VENTA', label: 'ID', type: 'number', required: true },
      { name: 'ID_SUCURSAL', label: 'Sucursal', type: 'number', required: false },
      { name: 'ID_CLIENTE', label: 'Cliente', type: 'number', required: false },
      { name: 'ID_FORMAPAGO', label: 'Forma de pago', type: 'number', required: false },
      { name: 'ID_EMPLEADO', label: 'Empleado', type: 'number', required: false },
      { name: 'FECHA_VENTA', label: 'Fecha', type: 'date', required: false },
      { name: 'TOTAL', label: 'Total', type: 'decimal', required: false },
    ],
  },
  Detalle_Venta: {
    label: 'Detalle de venta',
    description: 'Productos vendidos por venta.',
    primaryKey: ['ID_VENTA', 'ID_PRODUCTO'],
    accent: 'from-orange-500/20 to-orange-500/5',
    defaultSort: { field: 'ID_VENTA', direction: 'asc' },
    fields: [
      { name: 'ID_VENTA', label: 'Venta', type: 'number', required: true },
      { name: 'ID_PRODUCTO', label: 'Producto', type: 'number', required: true },
      { name: 'CANTIDAD_VENTA', label: 'Cantidad', type: 'number', required: true },
      { name: 'PRECIO_UNITARIO', label: 'Precio Unitario', type: 'decimal', required: false },
    ],
  },
  Traslado: {
    label: 'Traslados',
    description: 'Movimientos entre sucursales.',
    primaryKey: 'ID_TRASLADO',
    accent: 'from-slate-500/20 to-slate-500/5',
    defaultSort: { field: 'ID_TRASLADO', direction: 'desc' },
    fields: [
      { name: 'ID_TRASLADO', label: 'ID', type: 'number', required: true },
      { name: 'ID_SUCURSAL_ORIGEN', label: 'Sucursal origen', type: 'number', required: false },
      { name: 'ID_SUCURSAL_DESTINO', label: 'Sucursal destino', type: 'number', required: false },
      { name: 'FECHA_TRASLADO', label: 'Fecha', type: 'date', required: false },
    ],
  },
  Detalle_Traslado: {
    label: 'Detalle de traslado',
    description: 'Productos incluidos en traslados.',
    primaryKey: ['ID_TRASLADO', 'ID_PRODUCTO'],
    accent: 'from-cyan-400/20 to-cyan-400/5',
    defaultSort: { field: 'ID_TRASLADO', direction: 'asc' },
    fields: [
      { name: 'ID_TRASLADO', label: 'Traslado', type: 'number', required: true },
      { name: 'ID_PRODUCTO', label: 'Producto', type: 'number', required: true },
      { name: 'CANTIDAD', label: 'Cantidad', type: 'number', required: true },
    ],
  },
  Flujo_Caja: {
    label: 'Flujo de caja',
    description: 'Ingresos y egresos por sucursal.',
    primaryKey: 'ID_MOVIMIENTO',
    accent: 'from-green-500/20 to-green-500/5',
    defaultSort: { field: 'FECHA', direction: 'desc' },
    fields: [
      { name: 'ID_MOVIMIENTO', label: 'ID', type: 'number', required: true },
      { name: 'ID_SUCURSAL', label: 'Sucursal', type: 'number', required: false },
      { name: 'TIPO', label: 'Tipo', type: 'text', required: false },
      { name: 'MONTO', label: 'Monto', type: 'decimal', required: false },
      { name: 'FECHA', label: 'Fecha', type: 'date', required: false },
    ],
  },
  Tipo_Activo: {
    label: 'Tipos de activos',
    description: 'Clasificación de activos fijos.',
    primaryKey: 'ID_TIPOACTIVO',
    accent: 'from-amber-400/20 to-amber-400/5',
    defaultSort: { field: 'ID_TIPOACTIVO', direction: 'asc' },
    fields: [
      { name: 'ID_TIPOACTIVO', label: 'ID', type: 'number', required: true },
      { name: 'NOMBRE_TIPO', label: 'Nombre', type: 'text', required: true },
    ],
  },
  Activo_Fijo: {
    label: 'Activos fijos',
    description: 'Activos registrados por sucursal.',
    primaryKey: 'ID_ACTIVO',
    accent: 'from-stone-500/20 to-stone-500/5',
    defaultSort: { field: 'ID_ACTIVO', direction: 'asc' },
    fields: [
      { name: 'ID_ACTIVO', label: 'ID', type: 'number', required: true },
      { name: 'ID_TIPOACTIVO', label: 'Tipo de activo', type: 'number', required: false },
      { name: 'ID_SUCURSAL', label: 'Sucursal', type: 'number', required: false },
      { name: 'DESCRIPCION', label: 'Descripción', type: 'text', required: false },
      { name: 'VALOR_COMPRA', label: 'Valor compra', type: 'decimal', required: false },
    ],
  },
}

export default tableDefinitions
