export const tableDefinitions = {
  Departamento: {
    label: 'Departamentos',
    description: 'Departamentos operativos donde se ubican las sucursales.',
    primaryKey: 'ID_DEPARTAMENTO',
    accent: 'from-emerald-500/20 to-emerald-500/5',
    defaultSort: { field: 'ID_DEPARTAMENTO', direction: 'asc' },
    fields: [
      { name: 'ID_DEPARTAMENTO', label: 'ID', type: 'number', required: true, auto: true },
      { name: 'NOMBRE_DEPARTAMENTO', label: 'Nombre', type: 'text', required: true },
    ],
  },
  Municipio: {
    label: 'Municipios',
    description: 'Municipios por departamento.',
    primaryKey: 'ID_MUNICIPIO',
    accent: 'from-sky-500/20 to-sky-500/5',
    defaultSort: { field: 'ID_MUNICIPIO', direction: 'asc' },
    fields: [
      { name: 'ID_MUNICIPIO', label: 'ID', type: 'number', required: true, auto: true },
      { name: 'ID_DEPARTAMENTO', label: 'Departamento', type: 'number', required: true, references: 'Departamento', displayField: 'NOMBRE_DEPARTAMENTO' },
      { name: 'NOMBRE_MUNICIPIO', label: 'Nombre', type: 'text', required: true },
    ],
  },
  Sucursal: {
    label: 'Sucursales',
    description: 'Puntos de venta físicos.',
    primaryKey: 'ID_SUCURSAL',
    accent: 'from-purple-500/20 to-purple-500/5',
    defaultSort: { field: 'ID_SUCURSAL', direction: 'asc' },
    fields: [
      { name: 'ID_SUCURSAL', label: 'ID', type: 'number', required: true, auto: true },
      { name: 'ID_MUNICIPIO', label: 'Municipio', type: 'number', required: true, references: 'Municipio', displayField: 'NOMBRE_MUNICIPIO' },
      { name: 'DIRECCION', label: 'Dirección', type: 'text', required: true },
      { name: 'TIPO', label: 'Tipo', type: 'text', required: false },
    ],
  },
  Puesto: {
    label: 'Puestos',
    description: 'Catálogo de puestos con salarios base.',
    primaryKey: 'ID_PUESTO',
    accent: 'from-amber-500/20 to-amber-500/5',
    defaultSort: { field: 'ID_PUESTO', direction: 'asc' },
    fields: [
      { name: 'ID_PUESTO', label: 'ID', type: 'number', required: true, auto: true },
      { name: 'NOMBRE_PUESTO', label: 'Nombre', type: 'text', required: true },
      { name: 'SALARIO_BASE', label: 'Salario Base', type: 'decimal', required: false },
    ],
  },
  Empleado: {
    label: 'Empleados',
    description: 'Personal operativo y administrativo.',
    primaryKey: 'ID_EMPLEADO',
    accent: 'from-rose-500/20 to-rose-500/5',
    defaultSort: { field: 'ID_EMPLEADO', direction: 'asc' },
    fields: [
      { name: 'ID_EMPLEADO', label: 'ID', type: 'number', required: true, auto: true },
      { name: 'ID_SUCURSAL', label: 'Sucursal', type: 'number', required: true, references: 'Sucursal', displayField: 'DIRECCION' },
      { name: 'ID_PUESTO', label: 'Puesto', type: 'number', required: true, references: 'Puesto', displayField: 'NOMBRE_PUESTO' },
      { name: 'NOMBRE', label: 'Nombre', type: 'text', required: true },
      { name: 'APELLIDO', label: 'Apellido', type: 'text', required: true },
      { name: 'SALARIO', label: 'Salario', type: 'decimal', required: false },
    ],
  },
  Proveedor: {
    label: 'Proveedores',
    description: 'Fabricantes y distribuidores de productos.',
    primaryKey: 'ID_PROVEEDOR',
    accent: 'from-lime-500/20 to-lime-500/5',
    defaultSort: { field: 'ID_PROVEEDOR', direction: 'asc' },
    fields: [
      { name: 'ID_PROVEEDOR', label: 'ID', type: 'number', required: true, auto: true },
      { name: 'NOMBRE_PROVEEDOR', label: 'Nombre', type: 'text', required: true },
    ],
  },
  Tipo_Producto: {
    label: 'Tipos de Producto',
    description: 'Categorización de productos.',
    primaryKey: 'ID_TIPO_PRODUCTO',
    accent: 'from-cyan-500/20 to-cyan-500/5',
    defaultSort: { field: 'ID_TIPO_PRODUCTO', direction: 'asc' },
    fields: [
      { name: 'ID_TIPO_PRODUCTO', label: 'ID', type: 'number', required: true, auto: true },
      { name: 'CATEGORIA', label: 'Categoría', type: 'text', required: true },
    ],
  },
  Producto: {
    label: 'Productos',
    description: 'Catálogo general de productos.',
    primaryKey: 'ID_PRODUCTO',
    accent: 'from-fuchsia-500/20 to-fuchsia-500/5',
    defaultSort: { field: 'ID_PRODUCTO', direction: 'asc' },
    fields: [
      { name: 'ID_PRODUCTO', label: 'ID', type: 'number', required: true, auto: true },
      { name: 'ID_TIPO_PRODUCTO', label: 'Tipo', type: 'number', required: true, references: 'Tipo_Producto', displayField: 'CATEGORIA' },
      { name: 'ID_PROVEEDOR', label: 'Proveedor', type: 'number', required: true, references: 'Proveedor', displayField: 'NOMBRE_PROVEEDOR' },
      { name: 'NOMBRE_PRODUCTO', label: 'Nombre', type: 'text', required: true },
      { name: 'PRECIO_VENTA', label: 'Precio Venta', type: 'decimal', required: false },
      { name: 'COSTO', label: 'Costo', type: 'decimal', required: false },
      { name: 'STOCK_MINIMO', label: 'Stock Mínimo', type: 'number', required: false },
    ],
  },
  Inventario_Sucursal: {
    label: 'Inventario por Sucursal',
    description: 'Existencias de productos en cada sucursal.',
    primaryKey: ['ID_SUCURSAL', 'ID_PRODUCTO'],
    accent: 'from-blue-500/20 to-blue-500/5',
    defaultSort: { field: 'ID_SUCURSAL', direction: 'asc' },
    fields: [
      { name: 'ID_SUCURSAL', label: 'Sucursal', type: 'number', required: true, references: 'Sucursal', displayField: 'DIRECCION' },
      { name: 'ID_PRODUCTO', label: 'Producto', type: 'number', required: true, references: 'Producto', displayField: 'NOMBRE_PRODUCTO' },
      { name: 'CANTIDAD', label: 'Cantidad', type: 'number', required: true },
    ],
  },
  Cliente: {
    label: 'Clientes',
    description: 'Directorio de clientes registrados.',
    primaryKey: 'ID_CLIENTE',
    accent: 'from-teal-500/20 to-teal-500/5',
    defaultSort: { field: 'ID_CLIENTE', direction: 'asc' },
    fields: [
      { name: 'ID_CLIENTE', label: 'ID', type: 'number', required: true },
      { name: 'NOMBRE_CLIENTE', label: 'Nombre', type: 'text', required: false },
      { name: 'APELLIDO', label: 'Apellido', type: 'text', required: false },
      { name: 'TELEFONO', label: 'Teléfono', type: 'text', required: false },
    ],
  },
  Tipo_Pedido: {
    label: 'Tipos de Pedido',
    description: 'Clasificación de pedidos.',
    primaryKey: 'ID_TIPO_PEDIDO',
    accent: 'from-pink-500/20 to-pink-500/5',
    defaultSort: { field: 'ID_TIPO_PEDIDO', direction: 'asc' },
    fields: [
      { name: 'ID_TIPO_PEDIDO', label: 'ID', type: 'number', required: true, auto: true },
      { name: 'NOMBRE', label: 'Nombre', type: 'text', required: false },
    ],
  },
  Pedido: {
    label: 'Pedidos',
    description: 'Registro de pedidos de clientes.',
    primaryKey: 'ID_PEDIDO',
    accent: 'from-indigo-500/20 to-indigo-500/5',
    defaultSort: { field: 'ID_PEDIDO', direction: 'asc' },
    allowEdit: false,
    allowDelete: false,
    fields: [
      { name: 'ID_PEDIDO', label: 'ID', type: 'number', required: true, auto: true },
      { name: 'ID_CLIENTE', label: 'Cliente', type: 'number', required: false, references: 'Cliente', displayField: 'NOMBRE_CLIENTE' },
      { name: 'ID_TIPO_PEDIDO', label: 'Tipo Pedido', type: 'number', required: false, references: 'Tipo_Pedido', displayField: 'NOMBRE' },
      { name: 'FECHA_PEDIDO', label: 'Fecha', type: 'date', required: false },
      { name: 'TOTAL', label: 'Total', type: 'decimal', required: false },
    ],
  },
  Detalle_Pedido: {
    label: 'Detalle de Pedidos',
    description: 'Productos incluidos en cada pedido.',
    primaryKey: ['ID_PEDIDO', 'ID_PRODUCTO'],
    accent: 'from-emerald-400/20 to-emerald-400/5',
    defaultSort: { field: 'ID_PEDIDO', direction: 'asc' },
    allowEdit: false,
    allowDelete: false,
    fields: [
      { name: 'ID_PEDIDO', label: 'Pedido', type: 'number', required: true, references: 'Pedido', displayField: 'ID_PEDIDO' },
      { name: 'ID_PRODUCTO', label: 'Producto', type: 'number', required: true, references: 'Producto', displayField: 'NOMBRE_PRODUCTO' },
      { name: 'CANTIDAD', label: 'Cantidad', type: 'number', required: true },
      { name: 'PRECIO_UNITARIO', label: 'Precio Unitario', type: 'decimal', required: false },
    ],
  },
  Entrega: {
    label: 'Entregas',
    description: 'Programación de entregas de pedidos.',
    primaryKey: 'ID_ENTREGA',
    accent: 'from-yellow-500/20 to-yellow-500/5',
    defaultSort: { field: 'ID_ENTREGA', direction: 'asc' },
    allowEdit: false,
    allowDelete: false,
    fields: [
      { name: 'ID_ENTREGA', label: 'ID', type: 'number', required: true, auto: true },
      { name: 'ID_PEDIDO', label: 'Pedido', type: 'number', required: false, references: 'Pedido', displayField: 'ID_PEDIDO' },
      { name: 'ID_SUCURSAL', label: 'Sucursal', type: 'number', required: false, references: 'Sucursal', displayField: 'DIRECCION' },
      { name: 'FECHA_ESTIMADA', label: 'Fecha Estimada', type: 'date', required: false },
    ],
  },
  Forma_Pago: {
    label: 'Formas de Pago',
    description: 'Métodos de pago aceptados.',
    primaryKey: 'ID_FORMAPAGO',
    accent: 'from-violet-500/20 to-violet-500/5',
    defaultSort: { field: 'ID_FORMAPAGO', direction: 'asc' },
    fields: [
      { name: 'ID_FORMAPAGO', label: 'ID', type: 'number', required: true, auto: true },
      { name: 'NOMBRE_METODO', label: 'Método', type: 'text', required: true },
    ],
  },
  Venta: {
    label: 'Ventas',
    description: 'Registro histórico de ventas.',
    primaryKey: 'ID_VENTA',
    accent: 'from-red-500/20 to-red-500/5',
    defaultSort: { field: 'ID_VENTA', direction: 'desc' },
    allowEdit: false,
    allowDelete: false,
    fields: [
      { name: 'ID_VENTA', label: 'ID', type: 'number', required: true, auto: true },
      { name: 'ID_SUCURSAL', label: 'Sucursal', type: 'number', required: false, references: 'Sucursal', displayField: 'DIRECCION' },
      { name: 'ID_CLIENTE', label: 'Cliente', type: 'number', required: false, references: 'Cliente', displayField: 'NOMBRE_CLIENTE' },
      { name: 'ID_FORMAPAGO', label: 'Forma de pago', type: 'number', required: false, references: 'Forma_Pago', displayField: 'NOMBRE_METODO', badge: true },
      { name: 'ID_EMPLEADO', label: 'Empleado', type: 'number', required: false, references: 'Empleado', displayField: 'NOMBRE' },
      { name: 'FECHA_VENTA', label: 'Fecha', type: 'date', required: false },
      { name: 'TOTAL', label: 'Total', type: 'decimal', required: false },
    ],
  },
  Detalle_Venta: {
    label: 'Detalle de Ventas',
    description: 'Desglose de productos por venta.',
    primaryKey: ['ID_VENTA', 'ID_PRODUCTO'],
    accent: 'from-orange-500/20 to-orange-500/5',
    defaultSort: { field: 'ID_VENTA', direction: 'asc' },
    allowEdit: false,
    allowDelete: false,
    fields: [
      { name: 'ID_VENTA', label: 'Venta', type: 'number', required: true, references: 'Venta', displayField: 'ID_VENTA' },
      { name: 'ID_PRODUCTO', label: 'Producto', type: 'number', required: true, references: 'Producto', displayField: 'NOMBRE_PRODUCTO' },
      { name: 'CANTIDAD_VENTA', label: 'Cantidad', type: 'number', required: true },
      { name: 'PRECIO_UNITARIO', label: 'Precio Unitario', type: 'decimal', required: false },
    ],
  },
  Traslado: {
    label: 'Traslados',
    description: 'Movimientos de inventario entre sucursales.',
    primaryKey: 'ID_TRASLADO',
    accent: 'from-slate-500/20 to-slate-500/5',
    defaultSort: { field: 'ID_TRASLADO', direction: 'desc' },
    allowEdit: false,
    allowDelete: false,
    fields: [
      { name: 'ID_TRASLADO', label: 'ID', type: 'number', required: true, auto: true },
      { name: 'ID_SUCURSAL_ORIGEN', label: 'Sucursal origen', type: 'number', required: false, references: 'Sucursal', displayField: 'DIRECCION' },
      { name: 'ID_SUCURSAL_DESTINO', label: 'Sucursal destino', type: 'number', required: false, references: 'Sucursal', displayField: 'DIRECCION' },
      { name: 'FECHA_TRASLADO', label: 'Fecha', type: 'date', required: false },
    ],
  },
  Detalle_Traslado: {
    label: 'Detalle de Traslados',
    description: 'Productos incluidos en cada traslado.',
    primaryKey: ['ID_TRASLADO', 'ID_PRODUCTO'],
    accent: 'from-cyan-400/20 to-cyan-400/5',
    defaultSort: { field: 'ID_TRASLADO', direction: 'asc' },
    allowEdit: false,
    allowDelete: false,
    fields: [
      { name: 'ID_TRASLADO', label: 'Traslado', type: 'number', required: true, references: 'Traslado', displayField: 'ID_TRASLADO' },
      { name: 'ID_PRODUCTO', label: 'Producto', type: 'number', required: true, references: 'Producto', displayField: 'NOMBRE_PRODUCTO' },
      { name: 'CANTIDAD', label: 'Cantidad', type: 'number', required: true },
    ],
  },
  Flujo_Caja: {
    label: 'Flujo de Caja',
    description: 'Movimientos financieros por sucursal.',
    primaryKey: 'ID_MOVIMIENTO',
    accent: 'from-green-500/20 to-green-500/5',
    defaultSort: { field: 'FECHA', direction: 'desc' },
    allowEdit: false,
    allowDelete: false,
    fields: [
      { name: 'ID_MOVIMIENTO', label: 'ID', type: 'number', required: true, auto: true },
      { name: 'ID_SUCURSAL', label: 'Sucursal', type: 'number', required: false, references: 'Sucursal', displayField: 'DIRECCION' },
      { name: 'TIPO', label: 'Tipo', type: 'text', required: false, badge: true },
      { name: 'MONTO', label: 'Monto', type: 'decimal', required: false },
      { name: 'FECHA', label: 'Fecha', type: 'date', required: false },
    ],
  },
  Tipo_Activo: {
    label: 'Tipos de Activo',
    description: 'Clasificación de activos fijos.',
    primaryKey: 'ID_TIPOACTIVO',
    accent: 'from-amber-400/20 to-amber-400/5',
    defaultSort: { field: 'ID_TIPOACTIVO', direction: 'asc' },
    fields: [
      { name: 'ID_TIPOACTIVO', label: 'ID', type: 'number', required: true, auto: true },
      { name: 'NOMBRE_TIPO', label: 'Nombre', type: 'text', required: true },
    ],
  },
  Activo_Fijo: {
    label: 'Activos Fijos',
    description: 'Inventario de activos fijos.',
    primaryKey: 'ID_ACTIVO',
    accent: 'from-stone-500/20 to-stone-500/5',
    defaultSort: { field: 'ID_ACTIVO', direction: 'asc' },
    fields: [
      { name: 'ID_ACTIVO', label: 'ID', type: 'number', required: true, auto: true },
      { name: 'ID_TIPOACTIVO', label: 'Tipo', type: 'number', required: true, references: 'Tipo_Activo', displayField: 'NOMBRE_TIPO' },
      { name: 'ID_SUCURSAL', label: 'Sucursal', type: 'number', required: true, references: 'Sucursal', displayField: 'DIRECCION' },
      { name: 'DESCRIPCION', label: 'Descripción', type: 'text', required: true },
      { name: 'VALOR_COMPRA', label: 'Valor Compra', type: 'decimal', required: false },
    ],
  },
  Departamento: {
    label: 'Departamentos',
    description: 'Catálogo de departamentos.',
    primaryKey: 'ID_DEPARTAMENTO',
    accent: 'from-teal-500/20 to-teal-500/5',
    defaultSort: { field: 'NOMBRE_DEPARTAMENTO', direction: 'asc' },
    fields: [
      { name: 'ID_DEPARTAMENTO', label: 'ID', type: 'number', required: true, auto: true },
      { name: 'NOMBRE_DEPARTAMENTO', label: 'Nombre', type: 'text', required: true },
    ],
  },
  Municipio: {
    label: 'Municipios',
    description: 'Catálogo de municipios.',
    primaryKey: 'ID_MUNICIPIO',
    accent: 'from-cyan-500/20 to-cyan-500/5',
    defaultSort: { field: 'NOMBRE_MUNICIPIO', direction: 'asc' },
    fields: [
      { name: 'ID_MUNICIPIO', label: 'ID', type: 'number', required: true, auto: true },
      { name: 'ID_DEPARTAMENTO', label: 'Departamento', type: 'number', required: true, references: 'Departamento', displayField: 'NOMBRE_DEPARTAMENTO' },
      { name: 'NOMBRE_MUNICIPIO', label: 'Nombre', type: 'text', required: true },
    ],
  },
}
